#!/bin/bash
yum install -y git httpd
systemctl enable httpd 
systemctl start httpd
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
yum install -y nodejs 
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git .
rm -rf server
rm -rf exam

