#!/bin/bash
yum install -y git httpd
systemctl enable httpd 
systemctl start httpd
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
yum install -y nodejs 
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git .
rm -rf server
rm -rf exam
cd client
npm install 
wget https://raw.githubusercontent.com/ArdhanFah/user-data/main/client/.env
npm run generate
cp -r dist/* /var/www/html/
