#!/bin/bash
yum update -y
yum install git -y
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
yum install -y nodejs
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git
mv lks-apps-one/* ./
rm -rf client
rm -rf exam
cd server
echo "NODE_ENV=production\nPORT=8000\nDB_TYPE=mysql\nMYSQL_DB=db_campus\nMYSQL_USERNAME=admin\nMYSQL_PASSWORD=admin123456db\nMYSQL_HOST=database-1.cluster-cfa24763haxo.us-east-2.rds.amazonaws.com\nMYSQL_PORT=3306\nREDIS_HOST=master.myredis.9ez68d.use2.cache.amazonaws.com\nREDIS_PORT=6379\nREDIS_PASSWORD=admin123456redis\nAWS_ACCESS_KEY=AKIA4ETX7JVRR7PQGW7E\nAWS_SECRET_ACCESS_KEY=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\nAWS_BUCKET_NAME=bucketmea\nLOG_PATH=/var/www/html/server/tmp\nCACHE_PATH=/var/www/html/server/logs" > .env
npm install
npm run start-prod
