#!/bin/bash
yum update -y
yum install -y git httpd
systemctl enable httpd 
systemctl start httpd
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
yum install -y nodejs 
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git .
rm -rf server
rm -rf exam
cd client
npm install 
echo "API_URL=172.16.2.133:8000\nAPI_EXAM_URL=YOUR_API_BACKEND_SERVER_HOST" > .env
npm run generate
cp dist/* /var/www/html



