#!/bin/bash
yum install httpd git amazon-efs-utils -y
systemctl enable httpd
systemctl start httpd
cd /var/www/html/
git clone https://github.com/betuah/lks-apps-one.git .
rm -rf server/
rm -rf client/
cd exam/
wget https://raw.githubusercontent.com/ArdhanFah/user-data/main/exam/.env
cd ssl/
wget https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
cd ..
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -
yum install nodejs -y
npm install
npm run start-prod
