#!/bin/bash
yum install httpd git -y
systemctl enable httpd
systemctl start httpd
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
yum install nodejs -y
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git ./
rm -rf client/
rm -rf exam/
cd server/
wget https://raw.githubusercontent.com/ArdhanFah/user-data/main/server/.env
npm install
npm run start-prod
yum install amazon-efs-utils -y
mkdir -p tmp/
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-0eab594a570eea497.efs.us-east-2.amazonaws.com:/logs /var/www/html/server/logs
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-0eab594a570eea497.efs.us-east-2.amazonaws.com:/tmp /var/www/html/server/tmp
