#!/bin/bash
yum install httpd git -y
systemctl enable httpd
systemctl start httpd
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
yum install nodejs -y
cd /var/www/html
git clone https://github.com/betuah/lks-apps-one.git ./
rm -rf client/
rm -rf exam/
cd server
wget https://raw.githubusercontent.com/ArdhanFah/user-data/main/.env
npm install
npm run start-prod
yum install amazon-efs-utils -y
mkdir -p tmp/
mount -t efs -o tls fs-061339f1c3fbeae67:/ /var/www/html/server/logs
mount -t efs -o tls fs-061339f1c3fbeae67:/ /var/www/html/server/tmp
